### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

2 . Read numbers until 0 and print their mean and standard deviation without using a list.

##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [22]:
import numpy as np

def pairwise_row_distance(A):
    A = np.array(A, dtype=float)
    num_rows = A.shape[0]
    D = np.zeros((num_rows, num_rows), dtype=float)
    
    for i in range(num_rows):
        for j in range(num_rows):
            D[i][j] = np.sqrt(np.sum((A[i] - A[j]) ** 2))
    return D


In [23]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
# assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
# assert transpose(D) == D

In [24]:
D

array([[0.        , 2.44948974],
       [2.44948974, 0.        ]])

In [18]:
[1, 0, 2]
[0, 2, 1]

((1-0)**2 + (0-2)**2 + (2-1)**2)**0.5


2.449489742783178

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

13 . Inheritance

###### Guess the output without running the cell.

In [11]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


In [12]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True
True
False
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [25]:
import numpy as np

def standardize(matrix):    
    mean = np.mean(matrix, axis=1)
    standard_deviation = np.std(matrix, axis=0)
    standard_matrix = (matrix - mean[:, np.newaxis]) / standard_deviation
    return standard_matrix

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [26]:
import numpy as np
def normalize(matrix):
    # YOUR CODE HERE
    min_values = np.min(X, axis=0)
    max_values = np.max(X, axis=0)
    normalized_matrix = (matrix - min_values) / (max_values - min_values)

    return normalized_matrix

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0., 0., 1.],
       [1., 1., 0.]])

In [27]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)

In [16]:
class B:
    def __init__(self, public_value, private_value):
        self.this_is_public = public_value
        self.__this_is_private = private_value

# Create an instance of the class
obj = B("public", "private")

# Check the class's __dict__ attribute
print(obj.__dict__)

# Find the mangled name of the private attribute
mangled_name = obj._B__this_is_private
print("Mangled Name:", mangled_name)


{'this_is_public': 'public', '_B__this_is_private': 'private'}
Mangled Name: private
